"""Add usecase to connector_catalog

Revision ID: add_usecase_to_connector_catalog
Revises: 61bde7a59543
Create Date: 2026-03-08 08:36:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_usecase_to_connector_catalog'
down_revision = '61bde7a59543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector_catalog', sa.Column('usecase', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connector_catalog', 'usecase')
    # ### end Alembic commands ###
